//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int ArchivoId { get; set; }
        public int ArchivoVersion { get; set; }
        public string ArchivoNombre { get; set; }
        public Nullable<System.DateTime> ArchivoFecha { get; set; }
        public byte[] ArchivoData { get; set; }
        public Nullable<double> ArchivoMonto { get; set; }
        public string ArchivoComentario { get; set; }
        public string ArchivoExtension { get; set; }
        public Nullable<int> ArchivoEstado { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<int> CuentaActivaId { get; set; }
        public Nullable<System.DateTime> CuentaActivaFecha { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<System.DateTime> ArchivoFechaEliminacion { get; set; }
    
        public virtual CuentaActiva CuentaActiva { get; set; }
    }
}
