//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.CuentaActiva = new HashSet<CuentaActiva>();
        }
    
        public int CuentaId { get; set; }
        public string CuentaNumero { get; set; }
        public string CuentaNombre { get; set; }
        public Nullable<int> CuentaEmpresa { get; set; }
        public Nullable<int> CuentaRubro { get; set; }
        public Nullable<int> CuentaGrupo { get; set; }
        public string CuentaDescripcion { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaActiva> CuentaActiva { get; set; }
    }
}
