//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaActiva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaActiva()
        {
            this.Archivo = new HashSet<Archivo>();
            this.Log = new HashSet<Log>();
        }
    
        public int CuentaActivaId { get; set; }
        public System.DateTime CuentaActivaFecha { get; set; }
        public Nullable<int> CuentaActivaDiasPlazo { get; set; }
        public Nullable<int> CuentaActivaTotal { get; set; }
        public Nullable<int> AnalistaId { get; set; }
        public Nullable<int> ValidadorId { get; set; }
        public Nullable<int> CertificadorId { get; set; }
        public Nullable<int> CuentaActivaEstado { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual EstadoCuenta EstadoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivo> Archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Log { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
    }
}
