//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogId { get; set; }
        public string LogDescripcion { get; set; }
        public Nullable<int> LogEstadoId { get; set; }
        public Nullable<System.DateTime> LogFecha { get; set; }
        public Nullable<int> CuentaActivaId { get; set; }
        public Nullable<System.DateTime> CuentaActivaFecha { get; set; }
    
        public virtual CuentaActiva CuentaActiva { get; set; }
        public virtual EstadoCuenta EstadoCuenta { get; set; }
    }
}
