//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC.Models.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.CuentaActiva = new HashSet<CuentaActiva>();
            this.CuentaActiva1 = new HashSet<CuentaActiva>();
            this.CuentaActiva2 = new HashSet<CuentaActiva>();
        }
    
        public int UsuarioId { get; set; }
        public string UsuarioRut { get; set; }
        public string UsuarioNombre { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string UsuarioEmail { get; set; }
        public Nullable<int> PerfilId { get; set; }
        public string Username { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> pwdEstado { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaActiva> CuentaActiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaActiva> CuentaActiva1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaActiva> CuentaActiva2 { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
